### ISSUE TITLE
Driver Automation Tool - Site Server Settings greyed out

### ISSUE THREAD

**Issue by Olphare** [MSEndpointMgr/ConfigMgr#267]
Hi,

I have installed the Driver Automation Tool and when I go over to ConfigMgr Settings it's all greyed out.
Anything I have forgotten or done wrong?
![Annotation 2020-09-07 154105](https://user-images.githubusercontent.com/32131749/92393536-55442c00-f120-11ea-82ed-4223a0299825.png)

Regards,
Jørgen

**Comment by TokenRing** [comment]
For anyone else having this issue - I did briefly as well. By default when the program is first opened, on the first page "make & model selection" you have to change the "deployment platform" option from the default "download only" to one of the options that pertains to SCCM/MECM - for instance in my case, "configmgr - driver pkg".

Once you do that, go back to the Site Server settings page, and the options will no longer be greyed out.

(sorry to hijack your post olphare but I wanted to make sure there was some SEO for other people having this issue and a solution!)

**Comment by TokenRing** [comment]
As an aside @maurice-daly - perhaps the instructions on your page [here](https://msendpointmgr.com/modern-driver-management/#step-1-driver-automation-tool-and-driver-package-creation) should be in a different order?

- Launch the Driver Automation Tool and connect to your ConfigMgr environment by entering the name of your Site server, the Site code and click Connect To ConfigMgr in the ConfigMgr Settings tab. Additionally, specify the Package Storage Path to a location that will be used for the Package Source of each driver package the tool will create.

- In the Common Settings tab, specify a path to where the Driver Automation Tool will download the source files for the driver packages.

- We now need to select the Deployment Platform as ConfigMgr – Standard Pkg, then pick Drivers as the Download Type and pick your OS and Architecture.

I'd suggest swapping steps 1 and 3 around at least, since you can't do step 1 without having done step 3 (at least, afaik?)
