### ISSUE TITLE
 Apply Driver Package process failed, please refer to previous error or warning messages

### ISSUE THREAD

**Issue by korbinianotto** [MSEndpointMgr/ConfigMgr#316]
Task Sequence failed with error code 1 but cannot find any error in the log.
Task Sequence is running in DriverUpdate deployment mode.

-DriverUpdate -Endpoint "OTFSRVSCCM01.bergzeit.local"

any ideas?

[ApplyDriverPackage.log](https://github.com/MSEndpointMgr/ConfigMgr/files/6302719/ApplyDriverPackage.log)
[smsts.log](https://github.com/MSEndpointMgr/ConfigMgr/files/6302720/smsts.log)

**Comment by gspsteve** [comment]
Hi,
same here.

```
 - Retrieved a total of '22' driver packages from AdminService matching operational mode: Production
[ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages
```

maybe there is already a solution!?

**Comment by StefanB73** [comment]
Hi,

had the same issue. Please have a look at 
[DriverUpdate fails after retrieving number of driver packages with no real error. #77](https://github.com/MSEndpointMgr/ModernDriverManagement/issues/77)

Windows build table is referring to 20H2 as an integer instead of a string.
Open up the script in your favourite editor and replace $OSVersion = 20H2 (line 964) with $OSVersion = "20H2"

Regards Stefan

**Comment by korbinianotto** [comment]
that solved the problem. thanks!
